// AUTO-GENERATED by release/version.mjs — do not edit by hand.
export const APP_VERSION = "1.3.0";
export const APP_BUILD_DATE = "2026-06-25";
export const APP_COMMIT = "1e4627a";
export const RELEASE_NOTES: string[] = [
  "Folder library: drag-and-drop a book onto a folder, or long-press / right-click to move or copy",
  "Server-side cloud moves — re-foldering a synced book no longer re-uploads it",
  "Settings reorganised into collapsible Display, Fonts and Margins groups",
  "Fixed long-press selecting page text on Android",
  "Automatic versioning: release.sh bumps the version per commit and shows release notes in Help"
];
