// AUTO-GENERATED by release/version.mjs — do not edit by hand.
export const APP_VERSION = "1.2.0";
export const APP_BUILD_DATE = "2026-06-24";
export const APP_COMMIT = "f0b4503";
export const RELEASE_NOTES: string[] = [
  "Selective Google Drive sync — opt in per book; reading progress merges by furthest position",
  "Server-side cloud moves: re-foldering a synced book no longer re-uploads it",
  "Folder library with drag-and-drop and long-press move / copy",
  "Settings reorganised into collapsible Display, Fonts and Margins groups",
  "Text-to-speech and audiobook player with 0.25x–3x speed presets",
  "Offline eviction: auto-remove unopened downloads, re-fetch from cloud on open"
];
